### ISSUE TITLE
Support dyn Trait syntax

### ISSUE THREAD

**Issue by janhohenheim** [DavidDeSimone/mockitol#17]
[Edition Guide Documentation](https://rust-lang-nursery.github.io/edition-guide/2018/transitioning/traits/dyn-trait.html)

In Rust 2018, trait objects are going to be marked explicitly by writing `dyn` in front of them. `#[mock]` currently panics when encountering this syntax:

```rust
trait Foo {}

#[cfg_attr(test, mock)]
pub trait Bar {
    fn foo(foo: &dyn Foo);
}

```
Compiling this code results in the following error message.
```
error: custom attribute panicked
  --> environment/src/properties.rs:35:18
   |
35 | #[cfg_attr(test, mock)]
   |                  ^^^^^
   |
   = help: message: called `Result::unwrap()` on an `Err` value: "failed to parse item: \"pub trait Bar {\\n    fn foo(foo: &dyn Foo);\\n}\""
```

**Comment by DavidDeSimone** [comment]
Issue resolved as of release 0.8.0
